"use client";
import type { ClientToServerEvents, Player, Race, RaceMode, RaceResult, ServerToClientEvents, WordPacket } from "@typing/shared-types";
import { useEffect, useRef, useState } from "react";
import { io, type Socket } from "socket.io-client";

export function Multiplayer({ mode, wordCount, numbers, punctuation, inviteCode, onClose }: { mode: RaceMode; wordCount: 25|50|100; numbers:boolean; punctuation:boolean; inviteCode?:string; onClose:()=>void }) {
  const [token,setToken]=useState<string|null>(null); const [race,setRace]=useState<Race|null>(null); const [players,setPlayers]=useState<Player[]>([]); const [results,setResults]=useState<RaceResult[]>([]); const [packet,setPacket]=useState<WordPacket|null>(null); const [typed,setTyped]=useState("");const [error,setError]=useState("");
  const socket=useRef<Socket<ServerToClientEvents,ClientToServerEvents>|null>(null); const started=useRef(0);const completed=useRef(false);const raceId=useRef("");
  useEffect(()=>{fetch("/api/socket-token").then(async response=>{if(response.ok)setToken((await response.json()).token);else setError("Your session expired. Sign in again.")}).catch(()=>setError("Unable to reach the race server."));},[]);
  useEffect(()=>{if(!token)return;const client:Socket<ServerToClientEvents,ClientToServerEvents>=io(`${process.env.NEXT_PUBLIC_SOCKET_URL||"http://localhost:5000"}/race`,{auth:{token}});socket.current=client;client.on("connect_error",()=>setError("Unable to connect to multiplayer."));client.on("race:error",value=>setError(value.message));client.on("race:state",value=>{raceId.current=value.id;setRace(value);setPlayers(value.players);if(value.status==="running"&&!started.current)started.current=Date.now()});client.on("race:packet",setPacket);client.on("race:player-progress",player=>setPlayers(values=>values.map(value=>value.id===player.id?player:value)));client.on("race:results",setResults);client.emit("race:matchmake",{mode,wordCount,numbers,punctuation,inviteCode});return()=>{client.emit("race:leave",{raceId:raceId.current});client.disconnect()}},[inviteCode,mode,numbers,punctuation,token,wordCount]);
  const target=packet?.words.slice(0,wordCount).join(" ")||"";
  function type(value:string){if(race?.status!=="running"||completed.current)return;const next=value.slice(0,target.length);setTyped(next);socket.current?.emit("race:progress",{raceId:race.id,typedText:next});if(next.length===target.length){completed.current=true;socket.current?.emit("race:complete",{raceId:race.id,typedText:next,durationMs:Date.now()-started.current})}}
  return <div className="multiplayer"><div className="multiplayer-head"><div><h2>Live race</h2><p>{race?.status||"Finding players"} - starts with 3 players or after 10 seconds</p></div><button className="secondary" onClick={onClose}>Leave</button></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="player-list">{[0,1,2].map(index=>{const player=players[index];return <div className="player-row" key={index}><div className="player-label"><span>{player?.displayName||"Waiting for player"}</span><span>{player?.wpm||0} wpm</span></div><div className="progress"><i style={{width:`${player?.progress||0}%`}}/></div></div>})}</div>{target&&<div className="multiplayer-type"><div className="words">{[...target].map((char,index)=><span key={index} data-state={index<typed.length?(typed[index]===char?"correct":"wrong"):index===typed.length?"caret":"upcoming"}>{char}</span>)}</div><textarea aria-label="Multiplayer typing input" autoFocus value={typed} onPaste={event=>event.preventDefault()} onChange={event=>type(event.target.value)} disabled={race?.status!=="running"}/></div>}{results.length>0&&<p>Race complete. Validated WPM: {results[0].correctWpm}</p>}</div>;
}
