import { randomBytes } from "node:crypto";
import { FriendInvite } from "../models/index.js";
import { users } from "../repositories/user.repository.js";
import { races, raceResults } from "../repositories/race.repository.js";
import { HttpError } from "../lib/http-error.js";

async function ensureFriendCode(user:any){if(user.friendCode)return user.friendCode;for(let attempt=0;attempt<8;attempt++){const code=randomBytes(4).toString("hex").toUpperCase();if(!await users.findByFriendCode(code)){user.friendCode=code;await user.save();return code}}throw new HttpError(503,"Unable to create friend code")}
async function registeredUser(id:string){const user:any=await users.findById(id);if(!user)throw new HttpError(404,"User not found");await ensureFriendCode(user);return user}
export async function listFriends(userId:string){await registeredUser(userId);const user:any=await users.withFriends(userId);return{friendCode:user.friendCode,friends:(user.friendIds||[]).map((friend:any)=>({id:String(friend._id),displayName:friend.username,friendCode:friend.friendCode}))}}
export async function addFriend(userId:string,code:string){const user=await registeredUser(userId);const friend:any=await users.findByFriendCode(code);if(!friend)throw new HttpError(404,"Friend code not found");if(String(friend._id)===userId)throw new HttpError(400,"You cannot add yourself");await users.addMutualFriends(userId,String(friend._id));return{id:String(friend._id),displayName:friend.username,friendCode:friend.friendCode}}
async function requireFriend(userId:string,friendId:string){const user:any=await registeredUser(userId);if(!(user.friendIds||[]).some((id:any)=>String(id)===friendId))throw new HttpError(403,"This user is not your friend");return registeredUser(friendId)}
export async function friendStats(userId:string,friendId:string){const friend=await requireFriend(userId,friendId);const shared:any[]=await races.sharedMultiplayer(userId,friendId);const results:any[]=await raceResults.forRacesAndUsers(shared.map(race=>race._id),[userId,friendId]);const byRace=new Map<string,any[]>();for(const result of results){const key=String(result.raceId);byRace.set(key,[...(byRace.get(key)||[]),result])}let wins=0,losses=0,draws=0,totalWpm=0,friendTotalWpm=0;const history=[];for(const race of shared){const pair=byRace.get(String(race._id))||[];const mine=pair.find(value=>String(value.userId)===userId);const theirs=pair.find(value=>String(value.userId)===friendId);if(!mine||!theirs)continue;const comparison=mine.correctWpm-theirs.correctWpm||mine.accuracy-theirs.accuracy;const outcome=comparison>0?"win":comparison<0?"loss":"draw";if(outcome==="win")wins++;else if(outcome==="loss")losses++;else draws++;totalWpm+=mine.correctWpm;friendTotalWpm+=theirs.correctWpm;history.push({raceId:String(race._id),date:race.endsAt||race.createdAt,outcome,myWpm:mine.correctWpm,friendWpm:theirs.correctWpm,myAccuracy:mine.accuracy,friendAccuracy:theirs.accuracy})}const played=history.length;return{friend:{id:String(friend._id),displayName:friend.username,friendCode:friend.friendCode},summary:{played,wins,losses,draws,myAverageWpm:played?Math.round(totalWpm/played):0,friendAverageWpm:played?Math.round(friendTotalWpm/played):0},history:history.slice(0,50)}}
export async function createFriendInvite(userId:string,friendId:string,options:{mode:string;wordCount:number;numbers:boolean;punctuation:boolean}){await requireFriend(userId,friendId);const code=randomBytes(3).toString("hex").toUpperCase();const invite=await FriendInvite.create({code,inviterId:userId,inviteeId:friendId,options,expiresAt:new Date(Date.now()+15*60_000)});return{code:invite.code,expiresAt:invite.expiresAt}}
export async function listInvites(userId:string){const values:any[]=await FriendInvite.find({inviteeId:userId,expiresAt:{$gt:new Date()}}).sort({createdAt:-1}).populate("inviterId","username").lean();return values.map(value=>({code:value.code,from:{id:String(value.inviterId._id),displayName:value.inviterId.username},options:value.options,expiresAt:value.expiresAt}))}
export async function validateRaceInvite(code:string,userId:string){const invite:any=await FriendInvite.findOne({code:code.toUpperCase(),expiresAt:{$gt:new Date()}}).lean();if(!invite||![String(invite.inviterId),String(invite.inviteeId)].includes(userId))throw new HttpError(403,"Invalid or expired friend invitation");return invite}
